### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined function Timber\wp_timezone_string()

### ISSUE THREAD

**Issue by netm** [45-North-Ventures-LLC/jackpine#17]
Hi there, install went well but I am getting this error when I view the site:

```
Fatal error: Uncaught Error: Call to undefined function Timber\wp_timezone_string() in /var/www/html/wp-content/themes/jackpine-next/vendor/timber/timber/lib/Twig.php:316 Stack trace: #0 /var/www/html/wp-includes/class-wp-hook.php(286): Timber\Twig->set_defaults(Object(Twig\Environment)) #1 /var/www/html/wp-includes/plugin.php(208): WP_Hook->apply_filters(Object(Twig\Environment), Array) #2 /var/www/html/wp-content/themes/jackpine-next/vendor/timber/timber/lib/Loader.php(476): apply_filters('timber/loader/t...', Object(Twig\Environment)) #3 /var/www/html/wp-content/themes/jackpine-next/vendor/timber/timber/lib/Loader.php(101): Timber\Loader->get_twig() #4 /var/www/html/wp-content/themes/jackpine-next/vendor/timber/timber/lib/Timber.php(748): Timber\Loader->render('index.twig', Array, false, 'default') #5 /var/www/html/wp-content/themes/jackpine-next/vendor/timber/timber/lib/Timber.php(878): Timber\Timber::compile(Array, Array, false, 'default', true) #6 /var/www/html/wp-content/themes/jackpine-next/theme/index.php(22): Ti in /var/www/html/wp-content/themes/jackpine-next/vendor/timber/timber/lib/Twig.php on line 316 
```

**Comment by netm** [comment]
A ha! This was my problem...

"Timber 2.0 requires WordPress 5.3 or greater, but you are running WordPress 5.1.1. Please upgrade WordPress in order to use Timber 2.0."
