### ISSUE TITLE
Production package not working

### ISSUE THREAD

**Issue by adrianratajczak** [45-North-Ventures-LLC/jackpine#25]
Hi devs, 
I've got pure Jackpine installation on my local env with builded zip from yarn `run archive command`. 
Installing zip over themes in wp-admin doesn't work (missing style.css file) and uploaded it over FTP. 
When I tried to activate it I've got bunch of errors
`Warning: include(/usr/home/adrianratajczak/domains/divi.adrianratajczak.pl/public_html/wp-content/themes/jackpine/vendor/composer/../../src/JackpineSite.php): failed to open stream: No such file or directory in /usr/home/adrianratajczak/domains/divi.adrianratajczak.pl/public_html/wp-content/themes/jackpine/vendor/composer/ClassLoader.php on line 444 Warning: include(/usr/home/adrianratajczak/domains/divi.adrianratajczak.pl/public_html/wp-content/themes/jackpine/vendor/composer/../../src/JackpineSite.php): failed to open stream: No such file or directory in /usr/home/adrianratajczak/domains/divi.adrianratajczak.pl/public_html/wp-content/themes/jackpine/vendor/composer/ClassLoader.php on line 444 Warning: include(): Failed opening '/usr/home/adrianratajczak/domains/divi.adrianratajczak.pl/public_html/wp-content/themes/jackpine/vendor/composer/../../src/JackpineSite.php' for inclusion (include_path='.:/usr/local/share/pear') in /usr/home/adrianratajczak/domains/divi.adrianratajczak.pl/public_html/wp-content/themes/jackpine/vendor/composer/ClassLoader.php on line 444 Fatal error: Uncaught Error: Class 'Jackpine\JackpineSite' not found in /usr/home/adrianratajczak/domains/divi.adrianratajczak.pl/public_html/wp-content/themes/jackpine/theme/functions.php:18 Stack trace: #0 /usr/home/adrianratajczak/domains/divi.adrianratajczak.pl/public_html/wp-settings.php(525): include() #1 /usr/home/adrianratajczak/domains/divi.adrianratajczak.pl/public_html/wp-config.php(90): require_once('/usr/home/adria...') #2 /usr/home/adrianratajczak/domains/divi.adrianratajczak.pl/public_html/wp-load.php(37): require_once('/usr/home/adria...') #3 /usr/home/adrianratajczak/domains/divi.adrianratajczak.pl/public_html/wp-admin/admin.php(34): require_once('/usr/home/adria...') #4 /usr/home/adrianratajczak/domains/divi.adrianratajczak.pl/public_html/wp-admin/themes.php(10): require_once('/usr/home/adria...') #5 {main} thrown in /usr/home/adrianratajczak/domains/divi.adrianratajczak.pl/public_html/wp-content/themes/jackpine/theme/functions.php on line 18
`

Why? What I am missing? Attached my theme as zip file
[jackpine.zip](https://github.com/45-North-Ventures-LLC/jackpine/files/5792435/jackpine.zip)

**Comment by adrianratajczak** [comment]
I've got same issue on my local WP when I tried to install generated theme

![brave_ZENeNNhqmL](https://user-images.githubusercontent.com/1114801/104120883-8e90e080-533a-11eb-9931-dd4e373b8636.png)
