### ISSUE TITLE
Call to undefined function Timber\wp_timezone_string() error

### ISSUE THREAD

**Issue by netm** [45-North-Ventures-LLC/jackpine#28]
I'm using Docker and a fresh install of Wordpress. Have followed through the "Getting started" instructions and all is working fine (apart from 'yarn run plop' which doesn't seem to exist on the CLI). When I run 'yarn start' though I get in the browser:

`Fatal error: Uncaught Error: Call to undefined function Timber\wp_timezone_string() in /var/www/html/wp-content/themes/jackpine-netm/vendor/timber/timber/lib/Twig.php:316 Stack trace: #0 /var/www/html/wp-includes/class-wp-hook.php(286): Timber\Twig->set_defaults(Object(Twig\Environment)) #1 /var/www/html/wp-includes/plugin.php(208): WP_Hook->apply_filters(Object(Twig\Environment), Array) #2 /var/www/html/wp-content/themes/jackpine-netm/vendor/timber/timber/lib/Loader.php(476): apply_filters('timber/loader/t...', Object(Twig\Environment)) #3 /var/www/html/wp-content/themes/jackpine-netm/vendor/timber/timber/lib/Loader.php(101): Timber\Loader->get_twig() #4 /var/www/html/wp-content/themes/jackpine-netm/vendor/timber/timber/lib/Timber.php(748): Timber\Loader->render('index.twig', Array, false, 'default') #5 /var/www/html/wp-content/themes/jackpine-netm/vendor/timber/timber/lib/Timber.php(878): Timber\Timber::compile(Array, Array, false, 'default', true) #6 /var/www/html/wp-content/themes/jackpine-netm/theme/index.php(25): Ti in /var/www/html/wp-content/themes/jackpine-netm/vendor/timber/timber/lib/Twig.php on line 316 `

**Comment by netm** [comment]
Ah ha, I was running an older version of Wordpress that didn't support Timber
